export const ActionTypes = {
    FETCH_RANDOM_USER: 'FETCH_RANDOM_USER',
    FETCH_MANY_RANDOM_USERS: 'FETCH_MANY_RANDOM_USERS',
    STORE_RANDOM_USER: 'STORE_RANDOM_USER',
    PAGINATE_PAGE: 'PAGINATE_PAGE',
    ERROR: 'ERROR'
} 
